### ISSUE TITLE
Audio setup

### ISSUE THREAD

**Issue by ricardojlrufino** [ricardojlrufino/yicam_qrcode#1]
For the audio to work first you need to run the RMM application of the original firmware, it does audio initializations which I still haven't figured out how to do.

**Comment by roleoroleo** [comment]
Did you try to build this?
https://github.com/lindenis-org/lindenis-v536-softwinner/tree/master/eyesee-mpp/middleware/v316/sample/sample_ao

**Comment by ricardojlrufino** [comment]
Not yet...
I will test tomorrow ..

**Comment by ricardojlrufino** [comment]
![image](https://user-images.githubusercontent.com/515675/114293150-28674700-9a6a-11eb-991f-2e65c0c6580a.png)
My build of MPP framework  apparently it is configured to automatically initialize the DISPLAY, and it always gives an error. The libs I used (from MaxIIDevKit) apparently have no audio support.

**Comment by roleoroleo** [comment]
Found!
gpio 16
```
ioctl(fd, _IOC(0, 0x70, 0x10, 0x0), 0);
```

**Comment by ricardojlrufino** [comment]
Wow... god job !!!
